# Generated by Django 2.0.7 on 2019-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
