# Generated by Django 2.0.7 on 2019-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modifeid_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
