# Generated by Django 2.0.7 on 2019-08-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190803_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modifeid_datetime',
            new_name='modified_datetime',
        ),
    ]
