# Generated by Django 2.0.7 on 2019-08-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190803_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
