# Generated by Django 2.0.7 on 2019-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190803_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
