# Generated by Django 2.0.7 on 2019-08-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190803_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='DIV_ID',
        ),
    ]
