# Generated by Django 2.2.3 on 2019-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190804_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
